<a href="https://colab.research.google.com/github/nico99-99/data-science-bootcamp/blob/main/wprowadzenie_02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Norma wektora, dlugość wektora w R^2

In [ ]:
v1 = np.array([0, 4])
v1

array([0, 4])

In [ ]:
np.linalg.norm(v1)

4.0

Norma euklidesowa

In [ ]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

Odległość dwóch punktów na płaszczyźnie

In [ ]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])
np.linalg.norm(p - q)

5.0990195135927845

Mnoenie macierzy

In [ ]:
X = np.array([[5, 3], [3,9]])
Y = np.array([[1], [-1]])
print(X)
print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [ ]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [ ]:
Z.shape

(2, 1)

In [ ]:
X = np.array([[2, -1, 3],
              [3,1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [ ]:
np.dot(X,Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

Wyznacznik macierzy

In [ ]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

Ślad macierzy (suma elementów na przekątnej)

In [ ]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

Macierz jednostkowa

In [ ]:
np.eye(5, dtype = 'int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrotna

In [ ]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [ ]:
np.set_printoptions(precision = 4, suppress = True)
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz transponowana

In [ ]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [ ]:
A.T

array([[ 2, -1],
       [ 4,  3]])

Rozwiązywanie układów równań

X = A^-1*B

In [2]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [3]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [4]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [5]:
X.shape

(2, 1)